### PR TITLE
feat(inquirer): update codebase from inquirer to @inquirer/prompts

### PR DESCRIPTION
**Pull request by jharrell**
Resolves DA-1566

### CODE REVIEW

**Review by nikolasburk — COMMENTED** [review]
Generally looks good to me, but I left some questions in Slack that should be clarified before approving the PR.

**Review by nikolasburk — DISMISSED** [review]

**Comment by mhessdev** [comment]
Screenshot 2024-11-02 at 10 22 47 AM

Could we change the descriptions to look different than selected text? It doesn't stand out that its the description.

**Comment by mhessdev** [comment]
Could we add a description to "Explore other examples"

**Comment by mhessdev** [comment]
Is there anyway to change this? I selected the prisma starter project but it says its downloading the `databases/prisma-postgres` not a huge issue but may make people thing what is being downloaded is incorrect

Screenshot 2024-10-28 at 4 12 25 PM

**Comment by mhessdev** [comment]
Screenshot 2024-11-02 at 10 27 01 AM


once its done installing the cli hangs, you have to do cmd+c to get out of it, can we get past that? Maybe even default into cd'ing into the new folder?

**Review by mhessdev — CHANGES_REQUESTED** [review]
I left comments on the main thread, woops. Take the ones that don't have to do with this PR and make issues out of them. Fix the others.

**Review by mhessdev — APPROVED** [review]

**Pull request merged**
